version: 2  # Version of CircleCI
jobs:
  build:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Create venv and run unit test
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pytest

      - setup_remote_docker 
       
      - run:
        # installs a docker client that will be used to run the docker commands
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
         # Builds a docker image to push to Docker Hub
         # <docker_hub_username/repo_name:version>.
          name: Build Docker image
          command: docker build -t akobulife/flask-test:v1 .

      - run:
        # Pushes the Docker image you created to the Docker Hub.
          name: Push to Docker Hub
          command: |
            docker login -u akobulife -p BOLton419@
            docker push akobulife/flask-test:v1